import { Article, Project } from "../types";

export const ARTICLES: Article[] = [
  {
    id: 1,
    slug: "state-mgmt-2025",
    title: "Rethinking State Management in 2025",
    date: "2025-01-14",
    tag: "engineering",
    readTime: "8",
    lines: 312,
    views: 4820,
    excerpt: "Global state libraries are slowly becoming obsolete...",
    preview: `// before: massive redux store\nconst store = createStore(rootReducer);\n\n// after: colocated, composable\nconst useTask = create((set) => ({\n  tasks: [],\n  add: (t) => set(s => ({ tasks: [...s.tasks, t] }))\n}));`,
  },
  {
    id: 2,
    slug: "typography-clarity",
    title: "The Typography of Clarity",
    date: "2024-12-03",
    tag: "design",
    readTime: "5",
    lines: 187,
    views: 3102,
    excerpt:
      "Fonts carry the emotional weight of your content. Most engineers reach for Inter and move on. Here's the process I actually use — and why it changes how readers feel.",
    preview: `/* the combo that's been working for me */\n--f-display: 'Fraunces', serif;   /* emotive */\n--f-body:    'Source Serif 4';    /* readable */\n--f-mono:    'Fira Code', mono;   /* yours */`,
  },
  {
    id: 3,
    slug: "slow-web",
    title: "Building for the Slow Web",
    date: "2024-11-19",
    tag: "essay",
    readTime: "6",
    lines: 224,
    views: 6751,
    excerpt:
      "We've optimised latency to zero and lost something. An argument for deliberate pacing — artificial delays, thoughtful transitions, and the radical act of not being instant.",
    preview: `// a 300ms breath before the result\nawait sleep(300);\nconst data = await fetchResult();\n// counterintuitive but it feels better`,
  },
  {
    id: 4,
    slug: "css-grid-power",
    title: "CSS Grid: The Underrated Power",
    date: "2024-10-05",
    tag: "engineering",
    readTime: "10",
    lines: 401,
    views: 8934,
    excerpt:
      "Most devs use Grid for two-column layouts and stop. I spent a month using it exclusively. Here's what I found — including the parts I still can't believe work.",
    preview: `/* magazine layout in 4 lines */\n.layout {\n  grid-template-areas:\n    "hero hero sidebar"\n    "a    b    sidebar";\n}`,
  },
  {
    id: 5,
    slug: "rust-for-ts-devs",
    title: "Rust Through TypeScript Eyes",
    date: "2024-09-12",
    tag: "engineering",
    readTime: "12",
    lines: 548,
    views: 11203,
    excerpt:
      "I picked up Rust after 7 years of TypeScript. The mental model shift was jarring, then beautiful. Here's the map I wish I'd had on day one.",
    preview: `// TS: nullable with ??\nconst name = user?.name ?? "anon";\n\n// Rust: Option is explicit\nlet name = user.map(|u| u.name)\n            .unwrap_or("anon");`,
  },
  {
    id: 6,
    slug: "design-systems-at-scale",
    title: "Design Systems That Don't Rot",
    date: "2024-08-20",
    tag: "design",
    readTime: "7",
    lines: 289,
    views: 5430,
    excerpt:
      "Every design system starts clean and becomes a graveyard of edge cases. Here's how I've kept three of them alive past the 18-month mark.",
    preview: `// tokens, not magic numbers\nexport const space = {\n  xs: "0.25rem",  // 4px\n  sm: "0.5rem",   // 8px\n  md: "1rem",     // 16px\n  lg: "2rem",     // 32px\n} as const;`,
  },
  {
    id: 7,
    slug: "local-first-software",
    title: "The Case for Local-First Software",
    date: "2024-07-08",
    tag: "essay",
    readTime: "9",
    lines: 376,
    views: 9812,
    excerpt:
      "Your app loses network and dies. It shouldn't. Local-first is not just offline support — it's a different relationship between users and their data. I'm a convert.",
    preview: `// CRDTs make conflicts mergeable\nconst doc = new Y.Doc();\nconst tasks = doc.getArray('tasks');\n\n// sync when online, work always\ntasks.insert(0, [newTask]);`,
  },
  {
    id: 8,
    slug: "testing-philosophy",
    title: "My Testing Philosophy (after 8 years)",
    date: "2024-06-15",
    tag: "engineering",
    readTime: "6",
    lines: 251,
    views: 7340,
    excerpt:
      "I've written too many tests that gave false confidence, and too few that caught real bugs. Here's where I've landed — and what I'd tell my earlier self.",
    preview: `// test behaviour, not implementation\nit('shows error when email invalid', () => {\n  render(<Form />);\n  userEvent.type(email, 'notanemail');\n  userEvent.click(submit);\n  expect(screen.getByRole('alert')).toBeVisible();\n});`,
  },
];

export const PROJECTS: Project[] = [
  {
    id: 1,
    repo: "novita/meridian",
    title: "meridian",
    pinned: true,
    status: "active",
    desc: "geography-aware task manager — the inbox, reinvented",
    longDesc:
      "Tasks that know where you are. Meridian surfaces the right work based on your physical location — home, office, coffee shop. Built in React Native with a Rust sync engine. 800+ stars in 3 months.",
    stack: ["React Native", "MapboxGL", "Supabase", "Rust"],
    lang: "TypeScript",
    langColor: "#3178c6",
    stars: 847,
    forks: 64,
    year: "2025",
    demoUrl: "https://meridian.app",
    snippet: `const nearbyTasks = tasks\n  .filter(t => haversine(t.loc, here) < radius)\n  .sort((a,b) => a.priority - b.priority)\n  .slice(0, MAX_SURFACE);`,
  },
  {
    id: 2,
    repo: "novita/glyphset",
    title: "glyphset",
    pinned: true,
    status: "active",
    desc: "open-source font pairing via optical metrics",
    longDesc:
      "Stop guessing at font pairings. Glyphset analyses x-height ratios, weight contrast, and historical usage to score combinations algorithmically. Used by 2k+ designers.",
    stack: ["Next.js", "TypeScript", "OpenType.js", "Vercel"],
    lang: "TypeScript",
    langColor: "#3178c6",
    stars: 1203,
    forks: 127,
    year: "2024",
    snippet: `function harmonicScore(a: Font, b: Font): number {\n  const xRatio = a.xHeight / b.xHeight;\n  const wContrast = Math.abs(a.weight - b.weight);\n  return Math.abs(xRatio - PHI) + (wContrast < 200 ? 0.3 : 0);\n}`,
  },
  {
    id: 3,
    repo: "novita/driftlog",
    title: "driftlog",
    pinned: false,
    status: "stable",
    desc: "local-first journaling — no cloud, beautiful PDF exports",
    longDesc:
      "A desktop app built with Tauri and Rust. Your entries stay on your machine, full-stop. When you want to share, it composes them into genuinely beautiful typeset PDFs using a custom layout engine.",
    stack: ["Tauri", "React", "Rust", "PDF-lib"],
    lang: "Rust",
    langColor: "#dea584",
    stars: 562,
    forks: 38,
    year: "2024",
    snippet: `pub fn export_pdf(entries: &[Entry]) -> Result<Bytes> {\n  let mut doc = Document::new(PageSize::A4);\n  for entry in entries {\n    doc.push_page(render_entry(entry)?);\n  }\n  doc.finalise()\n}`,
  },
  {
    id: 4,
    repo: "novita/wavelength",
    title: "wavelength",
    pinned: false,
    status: "stable",
    desc: "real-time collaborative mood boards via websockets",
    longDesc:
      "Figma-style collaboration for mood boards. Drag images, text, and color swatches onto a shared canvas with sub-50ms sync. Uses a CRDT under the hood to handle conflicts gracefully.",
    stack: ["SvelteKit", "Socket.io", "CF R2", "Yjs"],
    lang: "TypeScript",
    langColor: "#3178c6",
    stars: 334,
    forks: 29,
    year: "2023",
    snippet: `socket.on('op', (op: Op) => {\n  doc.applyOp(op);          // CRDT merge\n  broadcast('sync', op, socket.id);\n  persist(op);              // durable log\n});`,
  },
  {
    id: 5,
    repo: "novita/tinyqueue",
    title: "tinyqueue",
    pinned: false,
    status: "stable",
    desc: "a 0-dependency priority queue in 40 lines of TypeScript",
    longDesc:
      "Sometimes you just need a min-heap and don't want to pull in lodash for it. Zero deps, fully typed, ~500 bytes gzipped. Has more GitHub stars than my actual apps, which is humbling.",
    stack: ["TypeScript"],
    lang: "TypeScript",
    langColor: "#3178c6",
    stars: 2841,
    forks: 183,
    year: "2023",
    snippet: `push(item: T, priority: number) {\n  this.heap.push({ item, priority });\n  this._bubbleUp(this.heap.length - 1);\n}`,
  },
  {
    id: 6,
    repo: "novita/svelte-transitions",
    title: "svelte-transitions",
    pinned: false,
    status: "archived",
    desc: "physics-based spring transitions for Svelte",
    longDesc:
      "Spring physics for Svelte before the ecosystem had good answers. Now largely superseded by Svelte Motion, but it still gets a few downloads a week which I find charming.",
    stack: ["Svelte", "TypeScript"],
    lang: "TypeScript",
    langColor: "#3178c6",
    stars: 189,
    forks: 21,
    year: "2022",
    snippet: `export function spring(node: Element, { stiffness = 0.15, damping = 0.8 }) {\n  let velocity = 0, current = 0;\n  // Hooke's law, discretised\n}`,
  },
];

export const TAG_COLORS: Record<
  string,
  { bg: string; text: string; darkBg: string; darkText: string }
> = {
  engineering: {
    bg: "rgba(49,120,198,0.12)",
    text: "#3178c6",
    darkBg: "rgba(49,120,198,0.2)",
    darkText: "#79b8ff",
  },
  design: {
    bg: "rgba(219,88,115,0.12)",
    text: "#c45a72",
    darkBg: "rgba(219,88,115,0.2)",
    darkText: "#f4a8b8",
  },
  essay: {
    bg: "rgba(94,158,85,0.12)",
    text: "#5a9a52",
    darkBg: "rgba(94,158,85,0.2)",
    darkText: "#85e89d",
  },
};

export const STATUS_META: Record<string, { label: string; color: string }> = {
  active: { label: "active", color: "#3fb950" },
  stable: { label: "stable", color: "#e3b341" },
  archived: { label: "archived", color: "#8b949e" },
};
